Test remote aarch64 builder
Signed-off-by: Henri Rosten <henri.rosten@unikie.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -88,6 +88,8 @@ jobs:
             target: microchip-icicle-kit-debug
           - arch: x86_64-linux
             target: doc
+          - arch: aarch64-linux
+            target: nvidia-jetson-orin-nx-debug
     if: |
       always() &&
       needs.authorize.result == 'success' &&
@@ -133,6 +135,23 @@ jobs:
             trusted-public-keys = ghaf-dev.cachix.org-1:S3M8x3no8LFQPBfHw1jl6nmP8A7cVWKntoMKN3IsEQY= cache.vedenemo.dev:RGHheQnb6rXGK5v9gexJZ8iWTPX6OcSeS56YeXYzOcg= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
             substituters = https://ghaf-dev.cachix.org?priority=20 https://cache.vedenemo.dev https://cache.nixos.org
             system-features = nixos-test benchmark big-parallel kvm
+            builders-use-substitutes = true
+            builders = @/etc/nix/machines
+      - name: Install SSH key for aarch64 builder
+        uses: shimataro/ssh-key-action@v2
+        with:
+          key: ${{ secrets.BUILDER_SSH_KEY }}
+          name: id_ed25519
+          known_hosts: ${{ vars.BUILDER_SSH_KNOWN_HOST }}
+          config: ${{ vars.BUILDER_SSH_CONFIG }}
+      - name: Configure aarch64 remote builder
+        run: |
+          sudo sh -c "echo '${{ vars.BUILDER_MACHINE_CONFIG }}' >/etc/nix/machines"
+          sudo sh -c "echo '${{ vars.BUILDER_SSH_KNOWN_HOST }}' >>/etc/ssh/ssh_known_hosts"
+      - name: Debug
+        run: |
+          sudo cat /etc/ssh/ssh_known_hosts || echo "Failed: cat /etc/ssh/ssh_known_hosts"
+          sudo cat $HOME/.ssh/known_hosts || echo "Failed: cat $HOME/.ssh/known_hosts"
       - name: Install cachix
         run: |
           nix-env -iA cachix -f https://cachix.org/api/v1/install
