Trial nix-fast-build
Signed-off-by: Henri Rosten <henri.rosten@unikie.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -164,19 +164,19 @@ jobs:
           sudo sh -c "umask 377; echo '${{ secrets.BUILDER_SSH_KEY }}' >/etc/nix/id_builder_key"
           sudo sh -c "echo '${{ vars.BUILDER_SSH_KNOWN_HOST }}' >>/etc/ssh/ssh_known_hosts"
           sudo sh -c "echo '${{ vars.BUILDER_MACHINE_CONFIG }}' >/etc/nix/machines"
-      - name: Install cachix
-        run: |
-          nix-env -iA cachix -f https://cachix.org/api/v1/install
-          echo "Using cachix version:"
-          cachix --version
       - name: Build ${{ matrix.arch }}.${{ matrix.target }}
         run: |
-          if [ "${{ secrets.CACHIX_AUTH_TOKEN }}" == "" ]; then
-            echo "::error::Missing CACHIX_AUTH_TOKEN, will not build"
-            exit 1
+          BUILDER=''
+          if [ "${{ matrix.arch }}" == "x86_64-linux" ]; then
+            BUILDER='github@build4.vedenemo.dev'
+          elif [ "${{ matrix.arch }}" == "aarch64-linux" ]; then
+            BUILDER='github@hetzarm.vedenemo.dev'
           else
-            echo "Running nix build, with cachix watch-exec"
-            cachix authtoken ${{ secrets.CACHIX_AUTH_TOKEN }}
-            cachix watch-exec -v ghaf-dev -- \
-              nix build .#packages.${{ matrix.arch }}.${{ matrix.target }}
+            echo "::error::Unknown architecture: '${{ matrix.arch }}'"
+            exit 1
           fi
+          nix run github:Mic92/nix-fast-build#nix-fast-build -- \
+            --flake .#packages.${{ matrix.arch }}.${{ matrix.target }} \
+            --remote "$BUILDER" \
+            --remote-ssh-option IdentityFile /etc/nix/id_builder_key \
+            --no-download --skip-cached --debug --no-nom
